<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="mu-582784.dhcp.missouri.edu" failures="2" tests="20" name="Default test" time="0.257" errors="0" timestamp="2025-05-07T19:50:33 CDT">
  <testcase classname="edu.mu.examplefortesting.tests.FailingTests" name="testBatchTransferWrongAssertion" time="0.004">
    <failure type="java.lang.AssertionError" message="Expected from.balance = 100.0, but got 50.0 expected [100.0] but found [50.0]">
      <![CDATA[java.lang.AssertionError: Expected from.balance = 100.0, but got 50.0 expected [100.0] but found [50.0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEquals(Assert.java:728)
at edu.mu.examplefortesting.tests.FailingTests.testBatchTransferWrongAssertion(FailingTests.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testBatchTransferWrongAssertion -->
  <testcase classname="edu.mu.examplefortesting.tests.FailingTests" name="testWithdrawNegativeAmount" time="0.001">
    <failure type="org.testng.TestException" message="
Method FailingTests.testWithdrawNegativeAmount()[pri:0, instance:edu.mu.examplefortesting.tests.FailingTests@4135c3b] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method FailingTests.testWithdrawNegativeAmount()[pri:0, instance:edu.mu.examplefortesting.tests.FailingTests@4135c3b] should have thrown an exception of type class java.lang.IllegalArgumentException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:863)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testWithdrawNegativeAmount -->
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="testDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="testDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="testOverdraft" time="0.0"/>
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="testWithdraw" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="testWithdraw" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.InterestTest" name="testAddInterest" time="0.209"/>
  <testcase classname="edu.mu.examplefortesting.tests.InterestTest" name="testAddInterest" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.002"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.0"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.003"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.002"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.002"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testConcurrentDeposit" time="0.002"/>
  <testcase classname="edu.mu.examplefortesting.tests.TransferTest" name="testBatchTransfer" time="0.001"/>
  <testcase classname="edu.mu.examplefortesting.tests.AccountTest" name="disabledTest" time="0.0">
    <ignored/>
  </testcase> <!-- disabledTest -->
</testsuite> <!-- Default test -->
